!FederatedExperimentConfig
experiment: !ExperimentConfig
  name: "FedAVMNIST-Congruent ${num_clients} ${num_rounds} ${data_distribution_strategy} ${global_fraction}"
  device: "cuda"
  train_print_interval_epochs: 1
  validation_print_interval_epochs: 1
  is_train: true
  is_test: true

model: !ModelConfig
  name: "AVMNIST"
  model_type: "AVMNIST"
  audio_encoder: !MNISTAudio
    conv_block_one_one_args: !ConvBlockArgs
      conv_one_in: 1
      conv_one_out: 32
    conv_block_one_two_args: !ConvBlockArgs
      conv_one_in: 32
      conv_one_out: 32
    conv_batch_norm: True
    conv_block_two_one_args: !ConvBlockArgs
      conv_one_in: 32
      conv_one_out: 64
    conv_block_two_two_args: !ConvBlockArgs
      conv_one_in: 64
      conv_one_out: 64
    conv_batch_norm: True
    hidden_dim: 64
  image_encoder: !MNISTImage
    conv_block_one_one_args: !ConvBlockArgs
      conv_one_in: 1
      conv_one_out: 32
    conv_block_one_two_args: !ConvBlockArgs
      conv_one_in: 32
      conv_one_out: 64
    conv_block_two_one_args: !ConvBlockArgs
      conv_one_in: 64
      conv_one_out: 64
    conv_block_two_two_args: !ConvBlockArgs
      conv_one_in: 64
      conv_one_out: 64
    hidden_dim: 128
    conv_batch_norm: True
  hidden_dim: 128
  dropout: 0.5
  fusion_fn: "concat"

cmams:
  a: !ModelConfig
    name: "Simple_CMAM"
    model_type: "Simple_CMAM"
    target_modality: !Modality image
    load_pretrained_encoder_state_for: []
    input_modalities:
      - !Modality audio
    association_network: !AssociationNetwork
      input_size: 64
      hidden_size: 64
      output_size: 128
      dropout: 0.4
      batch_norm: True
  i: !ModelConfig
    name: "Simple_CMAM"
    model_type: "Simple_CMAM"
    target_modality: !Modality audio
    load_pretrained_encoder_state_for: []
    input_modalities:
      - !Modality image
    association_network: !AssociationNetwork
      input_size: 128
      hidden_size: 128
      output_size: 64
      dropout: 0.5
      batch_norm: True
 

fed_config: !FedConfig
  num_clients: ${num_clients}
  num_rounds: ${num_rounds}
  modality_distribution_method: "congruent"
  client_selection: !ClientSelection
    strategy: "round_robin"
  aggregation: !Aggregation
    type: "fedavg"
    aggregation_method: "mean"
    aggregation_weights: "uniform"
  global_training: 
    epochs: 5
    batch_size: 32
    early_stopping: false
    early_stopping_patience: 15
    early_stopping_metric: "loss"
    num_modalities: 3
    optimizer: !Optimizer
      name: "Adam"
      default_kwargs:
        lr: 2e-4
        weight_decay: 0.00001
    loss_functions: !LossFunctionGroup
      cross_entropy: 
        loss_name: "cross_entropy"
        weight: 1.0  
  global_cmam_training: 
    epochs: 5
    batch_size: 32 
    early_stopping: false
    early_stopping_patience: 15
    early_stopping_metric: "loss"
    num_modalities: 3
    optimizer: !Optimizer
      name: "Adam"
      default_kwargs:
        lr: 2e-4
        weight_decay: 0.00001
    loss_functions: !LossFunctionGroup
      cmam: 
        loss_name: "cmam"
        loss_kwargs: {
          cosine_weight: 0.0,
          mse_weight: 1.0,
          mae_weight: 0.0,
          cls_weight: 0.00
        }
        weight: 1.0  
  client_training: 
    epochs: 5
    batch_size: 32
    early_stopping: false
    early_stopping_patience: 15
    early_stopping_metric: "loss"
    num_modalities: 3
    optimizer: !Optimizer
      name: "Adam"
      default_kwargs:
        lr: 2e-4
        weight_decay: 0.00001
    loss_functions: !LossFunctionGroup
      cross_entropy: 
        loss_name: "cross_entropy"
        weight: 1.0

  client_cmam_training: 
    epochs: 5
    batch_size: 32
    early_stopping: false
    early_stopping_patience: 15
    early_stopping_metric: "loss"
    num_modalities: 3
    optimizer: !Optimizer
      name: "Adam"
      default_kwargs:
        lr: 2e-4
        weight_decay: 0.00001
    loss_functions: !LossFunctionGroup
      cmam: 
        loss_name: "cmam"
        loss_kwargs: {
          cosine_weight: 0.0,
          mse_weight: 1.0,
          mae_weight: 0.0,
          cls_weight: 0.00
        }
        weight: 1.0


fed_data: !FedDataConfig
  distribution_strategy: ${data_distribution_strategy}  # or "non_iid"
  task_type: "classification"  # or "multilabel_classification"
  global_fraction: ${global_fraction}
  datasets:
    train: !DatasetConfig
      dataset: "AVMNIST"
      data_fp: "$DATA/avmnist/train_subset.csv"
      split: "train"
      target_modality: !Modality "MULTIMODAL"
      batch_size: 32
      client_batch_size: 32
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0
          !Modality image: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["ai"]
    validation: !DatasetConfig
      dataset: "AVMNIST"
      data_fp: "$DATA/avmnist/validation_subset.csv"
      split: "valid"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      batch_size: 32
      client_batch_size: 32

      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0
          !Modality image: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["ai", "a", "i"]
    test: !DatasetConfig
      dataset: "AVMNIST"
      data_fp: "$DATA/avmnist/test_subset.csv"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: false
      client_batch_size: 32
      batch_size: 32
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0
          !Modality image: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["ai", "a", "i"]

metrics:
  metrics:
    accuracy:
      function: "sklearn.metrics.accuracy_score"
      kwargs: {}
    balanced_accuracy:
      function: "sklearn.metrics.balanced_accuracy_score"
      kwargs: {}
    f1_macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
        zero_division: 0
    f1_micro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "micro"
        zero_division: 0
    f1_weighted:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    precision_macro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "macro"
        zero_division: 0
    precision_micro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "micro"
        zero_division: 0
    precision_weighted:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    recall_macro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    recall_micro: 
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "micro"
        zero_division: 0
    recall_weighted:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    ConfusionMatrix:
      function: "sklearn.metrics.confusion_matrix"
      kwargs:
        labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    MAE:
      function: "sklearn.metrics.mean_absolute_error"
      kwargs: {}
    MSE:
      function: "sklearn.metrics.mean_squared_error"
      kwargs: {}
  groups:
    classification: ["accuracy", "balanced_accuracy", "f1_macro", "f1_micro", "f1_weighted", "precision_macro", "precision_micro", "precision_weighted", "recall_macro", "recall_micro", "recall_weighted", "ConfusionMatrix"]
    reconstruction: ["MAE", "MSE"]

logging:
  log_path: "$EXP_PATH/wch4/{experiment_name}/logs/{run_id}"
  model_output_path: "$EXP_PATH/wch4/{experiment_name}/models/{run_id}"
  metrics_path: "$EXP_PATH/wch4/{experiment_name}/metrics/{run_id}"
  save_metric: "loss"
  monitor_path: "$EXP_PATH/wch4/{experiment_name}/monitoring/{run_id}"
